name: "Setup"
description: "Checkout and install project"
inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.9"
runs:
  using: "composite"
  steps:
      - name: Install Poetry
        run: pip3 install poetry
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install
        shell: bash
