name: "Setup"
description: "Checkout and install project"
inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.9"
runs:
  using: "composite"
  steps:
      - name: Install Poetry
        run: |
          export POETRY_HOME=$HOME/poetry
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==1.7.1
          sudo ln -s $POETRY_HOME/bin/poetry /usr/local/bin/poetry
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --without benchmark
        shell: bash
